### ISSUE TITLE
reload() does not work as it expects data to be data[lng][ns]

### ISSUE THREAD

**Issue by o-kasian** [i18next/i18next-node-remote-backend#5]
It turns out that
```javascript
const langLoaded = (!err && data) ? data[lng][ns] : data;
```
is always `undefined`, because data is already destructured

**Comment by jamuhl** [comment]
can you add a link to relevant code line?

**Comment by o-kasian** [comment]
yes, here https://github.com/i18next/i18next-node-remote-backend/blob/d3ae2ab7598328b08f4ca868aeaa439bf3e36e32/src/index.js#L122

**Comment by jamuhl** [comment]
right...feel free to provide a PR if needed to get fixed fast...else i will fix it asap.

**Comment by jamuhl** [comment]
should be in i18next-node-remote-backend@1.0.1
