### ISSUE TITLE
Backend is not loaded in Linux

### ISSUE THREAD

**Issue by eponte-ut** [i18next/i18next-node-remote-backend#8]
## Environment

i18next version: 15.0.9
i18next-node-remote-backend version: 1.0.1
Node versions: 8.x, 10.x

Integrated as:
```
    i18next
      .use(Backend) 
```

## Description

For some reason, when running on Linux (i.e. executing the code in a Lambda), [this condition](https://github.com/i18next/i18next/blob/19f0a89de310bff08011661afc61f76534acd2ac/i18next.js#L2113
) is evaluating to false and thus the backend is not loaded.

Mac works properly.

## Workaround
```
    i18next
      .use(Backend.default || Backend) 
```

**Comment by jamuhl** [comment]
do you `import` or `require` the Backend...are node versions the same on mac and the lambda

**Comment by eponte-ut** [comment]
> do you `import` or `require` the Backend...are node versions the same on mac and the lambda

`const Backend = require('i18next-node-remote-backend');`

**Comment by eponte-ut** [comment]
Node versions are the same, and we have tried both 10.x and 8.x

**Comment by fcastilloec** [comment]
I'm seeing this behavior on macOS and the workaround fix it.
I'm also using:
i18next version: 15.0.9, 15.1.3
i18next-node-remote-backend version: 1.0.1, 1.1.0
Node versions: 10.x
