### ISSUE TITLE
Allow loadPath option to be a function

### ISSUE THREAD

**Issue by KubaJastrz** [i18next/i18next-node-remote-backend#9]
I want to have a possibility to manipulate `loadPath` url based on current language and namespace, ie.

```ts
{
  backend: {
    loadPath(_lng: string, ns: string): string {
        const lng = manipulate(_lng);
        return `/locales/${lng}/${ns}.json`
    }
  }
}
```

If this issue gets accepted I can make a PR for this.

---
### Backstory

I store Chinese translations with locale codes `zh-Hans` and `zh-Hant`. [i18next-express-middleware](https://github.com/i18next/i18next-express-middleware) built-in header detector returns codes such as `zh`, `zh-CN` and `zh-TW`.

To work around this issue I've created custom header detector that converts "browser" codes into accepted ones, but it would be so much simpler if I could just transform codes where they are actually used and not during the input detection.

**Comment by jamuhl** [comment]
zh-Hans, zh-Hant != zh-CN, zh-TW

Hans, Hant -> are specifications for type used traditional vs. simplified

CN, TW -> define the region / country were it is used.

So `zh-TW` is in most cases `zh-Hant-TW` and `zh-CN` is using simplified `zh-Hans-CN`

Should be possible to achieve this by using https://www.i18next.com/principles/fallback#fallback-language with extended fallback options.

If you prefer a PR i would do it in i18next before passing it to the backend -> so you can manipulate everywhere without having to change every backend implementation out there...https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L135

**Comment by KubaJastrz** [comment]
Yes, I am aware about the semantics. It's just how the translation system is implemented (I have no control over that).

I will look into the main package you linked, thanks.

**Comment by jamuhl** [comment]
Should be something like:

https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L135 -> `const changedLng = this.options.changeLngBeforeBackendRead(lng);`

in defaults https://github.com/i18next/i18next/blob/master/src/defaults.js#L1 -> `changeLngBeforeBackendRead: lng => lng`

Doing a PR would be awesome if you do it both for the lng and ns param: So users can change both.

**Comment by KubaJastrz** [comment]
I found out that `i18next-xhr-backend` does what I want on its own - https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L39-L42

edit: and so does `i18next-node-fs-backend` https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L79-L82

**Comment by jamuhl** [comment]
right...can be used...i18next has so many options to reach what users want - even i forgot some ;)

**Comment by KubaJastrz** [comment]
So, we have 2 options:
- leave the implementation of `loadPath` for each backend separately and add a possibility for a function to be passed in this backend,
- implement two new backend options (`changeLngBeforeBackendRead`, `changeNsBeforeBackendRead`) in the main library that will unify backend implementations for this particular feature


Edit:

I personally think that the function parameter is more intuitive to use, but on the other hand it's more expensive in terms of maintenance. And as seen above, is implemented inconsistently between different backends.

**Comment by jamuhl** [comment]
Guess the new options wouldn't hurt...and it's not like adding a lot of code to be maintained in future...so i'm ok with a PR for that in the main repo.
